- name: Deploy to Heroku
  uses: AkhileshNS/heroku-deploy@v3.5.7

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dental-plus-manager" #Must be unique in Heroku
          heroku_email: "bhrochamail@gmail.com"
          appdir: "back-end-db" # <- This will point to the api folder in your project
